version: 2
updates:
  - package-ecosystem: npm
    directories:
      - "/"
      - "/apps/workshop"
    schedule:
      interval: weekly
    groups:
      playwright:
        patterns:
          - "playwright"
          - "@playwright/*"
      npm-and-yarn:
        patterns:
          - "*"
        exclude-patterns:
          - "playwright"
          - "@playwright/*"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
